// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMNSNNwLSsoU7r-w6zm9Ml-L6AFsiqOA',
    appId: '1:910738399535:web:da0515347ff418309f81da',
    messagingSenderId: '910738399535',
    projectId: 'weight-e8884',
    authDomain: 'weight-e8884.firebaseapp.com',
    storageBucket: 'weight-e8884.appspot.com',
    measurementId: 'G-30VTNGE30M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhx11h5BmMDFKRA-BbTcEhQUyfaRiVXm4',
    appId: '1:910738399535:android:05677ea9f994be0d9f81da',
    messagingSenderId: '910738399535',
    projectId: 'weight-e8884',
    storageBucket: 'weight-e8884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqclq82GtxKH5S0byS8104mUhylJL7GDE',
    appId: '1:910738399535:ios:9c266c95a2532c489f81da',
    messagingSenderId: '910738399535',
    projectId: 'weight-e8884',
    storageBucket: 'weight-e8884.appspot.com',
    iosClientId: '910738399535-qke02i7oop4hgujp5gaajtgh00so9943.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqclq82GtxKH5S0byS8104mUhylJL7GDE',
    appId: '1:910738399535:ios:9c266c95a2532c489f81da',
    messagingSenderId: '910738399535',
    projectId: 'weight-e8884',
    storageBucket: 'weight-e8884.appspot.com',
    iosClientId: '910738399535-qke02i7oop4hgujp5gaajtgh00so9943.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );
}
